### ISSUE TITLE
Autofill use case / misuse / backstory

### ISSUE THREAD

**Issue by jacob-barna** [jacob-barna/TripleJR#13]

**Comment by ramirezronald** [comment]
Autofill was combined with Password use case. Has now changed to 3rd party extensions due to our discussion from class last time. Is this accurate @nebskers ?

**Comment by nebskers** [comment]
Yes, that is accurate @ramirezronald

**Comment by nebskers** [comment]
We are now calling the 5th case "3rd party extensions"

**Comment by ramirezronald** [comment]
Thanks for verifying  !

**Comment by ramirezronald** [comment]
Third-party extensions is now finalized. Feel free to review when you get the chance.
