### ISSUE TITLE
Browse use case / misuse / backstory

### ISSUE THREAD

**Issue by jacob-barna** [jacob-barna/TripleJR#17]
Completed #17

**Comment by ramirezronald** [comment]
Jeff, I don't think your picture added correctly can you verify?

**Comment by cyb3rc0wb0y** [comment]
Ronald, the link has been fixed and the image for use case is present.

**Comment by cyb3rc0wb0y** [comment]
I've also updated the image to include the revision of the use case/misuse cases.

**Comment by cyb3rc0wb0y** [comment]
![broswer_use_case](https://user-images.githubusercontent.com/25576618/66060330-1581c700-e503-11e9-9dc1-eaab11b6b30a.png)

**Comment by cyb3rc0wb0y** [comment]
Working to re-write the use case and misuse can to include the words "threatens", "includes", and "prevents" to mirror the image.

**Comment by nebskers** [comment]
@cyb3rc0wb0y  That's a good idea to make sure the words "threatens", "includes" and "prevents" are used. I am going to take a second look at mine.

**Comment by cyb3rc0wb0y** [comment]
<img width="1262" alt="Screen Shot 2019-10-02 at 8 06 52 PM" src="https://user-images.githubusercontent.com/25576618/66092146-6835a000-e550-11e9-9025-aafca83fb06a.png">

**Comment by cyb3rc0wb0y** [comment]
![Use Case Diagram - Page 9](https://user-images.githubusercontent.com/25576618/66092224-d8dcbc80-e550-11e9-8563-3f5f7dc36321.png)
