### ISSUE TITLE
Wallet - Identify an assurance claim and prepare a convincing argument to support your claim.

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#24]

**Comment by ramirezronald** [comment]
Have a rough draft for next class (10/9) so we can review as a team.

**Comment by ramirezronald** [comment]
Assurance claim being worked on for the wallet rewards.

**Comment by cyb3rc0wb0y** [comment]
@ramirezronald and @jacob-barna  do we need to create a 5th issue for SSL?

**Comment by nebskers** [comment]
We can probably take away the extensions for SSL?

**Comment by ramirezronald** [comment]
@cyb3rc0wb0y @nebskers it should be there, i re-opened the issue. check again please.

**Comment by cyb3rc0wb0y** [comment]
Thanks for looking, I was unaware it was closed at that time.
