### ISSUE TITLE
Browser Shields - Identify an assurance claim and prepare a convincing argument to support your claim.

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#25]

**Comment by ramirezronald** [comment]
Have a rough draft for next class (10/9) so we can review as a team. @cyb3rc0wb0y

**Comment by cyb3rc0wb0y** [comment]
@ramirezronald the issue has been moved to open on the board and is being processed to develop the assurance claim.

**Comment by jacob-barna** [comment]
@cyb3rc0wb0y - did you see the hullabaloo around the whitelist of third party requests and cookies?  Some users are claiming that "Brave Browser Sacrifices Security" 

https://www.netsparker.com/blog/web-security/brave-browser-sacrifices-security/

**Comment by cyb3rc0wb0y** [comment]
@jacob-barna that is a good document outline the issue(s) with whitelisting some of the biggest data collectors out there to "allow functionality" with the site and scripts.

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - Browsing](https://user-images.githubusercontent.com/25576618/66603129-1785fe80-eb71-11e9-9f19-21ae9b697e83.png)

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - Browsing](https://user-images.githubusercontent.com/25576618/66617138-70698d00-eb99-11e9-887a-4339726b8dbf.png)

**Comment by cyb3rc0wb0y** [comment]
I've modified my image, as shown above, with more exact evidence. Looking at code to possibly add lines of code to evidence where functions implemented.

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - Browsing](https://user-images.githubusercontent.com/25576618/66690060-51c7cc80-ec53-11e9-92a3-4ef1747b7460.png)

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - Browsing](https://user-images.githubusercontent.com/25576618/66693042-20a6c680-ec6a-11e9-8da0-1321cfde1375.png)
