### ISSUE TITLE
Password Manager - Identify an assurance claim and prepare a convincing argument to support your claim.

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#27]

**Comment by ramirezronald** [comment]
Have a rough draft for next class (10/9) so we can review as a team. @nebskers

**Comment by cyb3rc0wb0y** [comment]
@nebskers do you mind taking a look at my rebuttals?

**Comment by nebskers** [comment]
Yes - I am taking a look and doing the diagram now.  I have the context and 2 rebuttals right now.

**Comment by nebskers** [comment]
Can someone take a look at my diagram and see if you have anything to add or change?

**Comment by cyb3rc0wb0y** [comment]
I'm taking a look now. I can provide feedback tomorrow for you.

**Comment by cyb3rc0wb0y** [comment]
Just a reminder to complete the paragraph explaining your assessment, evidence, and gaps if any. I'm working on mine and will have it up for review.

**Comment by ramirezronald** [comment]
@nebskers i think your Rebuttal R2 & R3 are redundant. See Lucidchart for more info. Will need to re-word left side.
