### ISSUE TITLE
Extensions - Identify an assurance claim and prepare a convincing argument to support your claim

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#29]
Someone will have to create two assurance claims. Will discuss later. 

Assigned to group, however @ramirezronald and @cyb3rc0wb0y have got the claim started. @cyb3rc0wb0y will continue to refine it.

**Comment by jacob-barna** [comment]
@ramirezronald @cyb3rc0wb0y @nebskers 

Hey! look what I found!    This tool uses several methods (static analysis, external domains/communications/blacklists) to assess the security risk of extensions.

Why doesn't the browser warn us when we attempt to install fishy extensions?

**Comment by cyb3rc0wb0y** [comment]
@jacob-barna I'm currently looking more into the extensions and the scanning or warning of extensions. I'll keep you updated.

**Comment by jacob-barna** [comment]
here's another site that has more details about crxcavator
https://duo.com/blog/crxcavator

**Comment by cyb3rc0wb0y** [comment]
Working issue.

**Comment by cyb3rc0wb0y** [comment]
From the Brave FAQ: Why build a browser and not extensions for top browsers?
Extensions face API and performance limits. Additionally, popular extension stores often host malicious counterfeit extensions, which have lead to millions of infected users. Building our own browser lets us put our best foot forward on matters of speed and privacy. We may do extensions if our users find themselves browsing in other browsers often.

^^The above has a link to this page https://www.hackread.com/20-million-chrome-users-have-installed-fake-malicious-ad-blockers/ describing the threat the extensions can create.

**Comment by cyb3rc0wb0y** [comment]
Chrome's statement regarding extension policy to mitigate threats: https://blog.chromium.org/2015/05/continuing-to-protect-chrome-users-from.html

**Comment by ramirezronald** [comment]
@cyb3rc0wb0y will be reviewing that shortly .

**Comment by cyb3rc0wb0y** [comment]
Chromium blog post: https://blog.chromium.org/2018/10/trustworthy-chrome-extensions-by-default.html

**Comment by cyb3rc0wb0y** [comment]
@ramirezronald I'm trying to determine how to end the "chain" if we are proving it wrong. Evidence? Claim that it doesn't work followed by evidence?

**Comment by nebskers** [comment]
I have this same question.  The rebuttal is actually correct and there's no evidence or claim to go against it

**Comment by cyb3rc0wb0y** [comment]
I've completed a rough draft of the extensions case if anyone can review, edit, add to what they think.

**Comment by nebskers** [comment]
Thanks Jeff

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - HTTPS](https://user-images.githubusercontent.com/25576618/66690083-6dcb6e00-ec53-11e9-9bcf-468d8ba389ac.png)

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - 3rd Party Extension](https://user-images.githubusercontent.com/25576618/66690105-889de280-ec53-11e9-9c6d-63c1f9b4406b.png)

**Comment by ramirezronald** [comment]
nice !

**Comment by cyb3rc0wb0y** [comment]
![Assurance Claims - 3rd Party Extension](https://user-images.githubusercontent.com/25576618/66693686-2653da80-ec71-11e9-9477-e3f3838dfabc.png)
