### ISSUE TITLE
Short Summary of our code review strategy

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#43]
What challenges did you anticipate and how did your code review strategy attempt to address those challenges?

**Comment by nebskers** [comment]
This will be submitted by tonight.  Please let me know of any changes that I need to make. I'm going to try to be online the day we turn in so I can summarize the team collaboration and submit link

**Comment by ramirezronald** [comment]
Just saw your comment on this issue @nebskers thanks for getting things started! Please let us know any feedback/comments on anything we've got up so far
