### ISSUE TITLE
Findings from automated code scanning (if available). Include links to full reports.

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#45]

**Comment by ramirezronald** [comment]
Note to self - continue reviewing the breakdown from the report. Also, don't forget to upload full results/report.

**Comment by cyb3rc0wb0y** [comment]
Running brave/tracking-protection and brave/ad-block through mir-swamp. Utilizing C++ tools on Ubuntu platforms.

**Comment by cyb3rc0wb0y** [comment]
Haven't been able to successfully run MIR-SWAMP with any of the C++ code, however was able to run web script test on MIR-SWAMP for tracking-protection without errors. Flawfinder was used to check both ad-block and tracking-proctection code.

**Comment by ramirezronald** [comment]
> Haven't been able to successfully run MIR-SWAMP with any of the C++ code, however was able to run web script test on MIR-SWAMP for tracking-protection without errors. Flawfinder was used to check both ad-block and tracking-proctection code.

no worries @cyb3rc0wb0y that tool was giving me issues as well.

**Comment by cyb3rc0wb0y** [comment]
> > Haven't been able to successfully run MIR-SWAMP with any of the C++ code, however was able to run web script test on MIR-SWAMP for tracking-protection without errors. Flawfinder was used to check both ad-block and tracking-proctection code.
> 
> no worries @cyb3rc0wb0y that tool was giving me issues as well.

Thanks @ramirezronald, I ended up using flawfinder for the C++ and using mir-swamp just for the web scripting. I also tried checking the python code and attempting to run RUST, but wasn't successful with those.
