### ISSUE TITLE
Summary of key findings from manual and/or automated scanning. This summary may include categorization, mappings to CWEs, CAPECs, Risk Levels, etc.

### ISSUE THREAD

**Issue by ramirezronald** [jacob-barna/TripleJR#46]

**Comment by ramirezronald** [comment]
I've added a summary of my key findings. Let me know if i should fix anything

**Comment by cyb3rc0wb0y** [comment]
> I've added a summary of my key findings. Let me know if i should fix anything

I uploaded code snip of the base.h code for the snprintf and vsnprintf that was found by flawfinder. Reviewed your key findings and they look good to me, very detailed.
